### ISSUE TITLE
Always redirects to Login-Page

### ISSUE THREAD

**Issue by McBane87** [webdevnerdstuff/amazon-smile-redirect#29] opened 2020-04-02 13:25 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'amazon.de'
2. Click on 'nothing'
3. Scroll down to 'nothing'

**Expected behavior**
Replace the host part of the url to smile.amazon.de and keep the rest of the url as it was. Don't redirect to login page.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Chrome Version 80

**Additional context**
Even though I'm already loged in to amazon.de and smile.amazon.de this plugin always redirects me to the login page of smile.amazon.de.

**Comment by webdevnerdstuff** [comment] 2020-04-02 15:26
I see what the problem is. Looks like a small change on Amazon's side of things. I should have a fix for this soon.

**Comment by webdevnerdstuff** [comment] 2020-04-02 15:49
I have just pushed the updated code to the Chrome store. I'm not sure how long it will take to publish as their review times are taking longer currently due to the current COVID-19 situation. I will try to let you know here once it has been approved and published.

**Comment by McBane87** [comment] 2020-04-03 05:29
Thank you. The Update is already online and it's working :-)

**Closed** 2020-04-03 15:42 UTC
Labels: Chrome Extension, Update
